import { siteImages } from '../data/siteImages.js'
import { content } from '../data/content.js'
import { asset } from '../config/deployment.js'

/**
 * Everything <Media> needs for one of the site's own illustrative images:
 *
 *   <Media {...siteImage('hero')} ratio="16 / 9" sizes="100vw" />
 *
 * `siteImages` is generated by `npm run images`; the matching bilingual alt text
 * lives in content.siteImageAlt. These are licensed photographs used to
 * illustrate the pages (see CREDITS.md) — never the company's own projects,
 * which come from src/data/projects.js instead.
 *
 * A missing key falls back to the labelled placeholder block rather than a
 * broken image.
 */
export function siteImage(name, label) {
  const entry = siteImages[name]
  if (!entry) {
    return { src: null, label: label ?? { fr: 'PHOTO À FOURNIR', en: 'PHOTO TO BE PROVIDED' } }
  }
  return {
    // The generated paths are root-relative; asset() puts them under the base
    // the site is deployed to.
    src: asset(entry.src),
    sources: entry.sources?.map((source) => ({ ...source, src: asset(source.src) })),
    width: entry.width,
    height: entry.height,
    alt: content.siteImageAlt[name],
    label: content.siteImageAlt[name],
  }
}

export default siteImage
